artifacts_root: artifacts

data_ingestion:
 root_dir: artifacts/data_ingestion
 source_url: https://github.com/mayurkadam9833/Datasets/raw/refs/heads/main/AI_HUMAN_TEXT.zip
 local_data_file: artifacts/data_ingestion/AI_HUMAN_TEXT.zip
 unzip_dir: artifacts/data_ingestion

